# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "71bb3e596c4d47a083ac1c3b4a36d43c"
application_url = "https://example.com"
embedded = true
name = "announcement-app"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[webhooks]
api_version = "2026-07"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
